plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zyf.bianjie'
    compileSdk 34

    defaultConfig {
        applicationId "com.zyf.bianjie"
        minSdk 24
        targetSdk 34
        versionCode 110
        versionName "1.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.8.0'
}
